name: Backend CI/CD - Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure (KodeKloud provided SP)
      - name: Azure Login
        uses: azure/login@v2
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Login to ACR using admin credentials
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      # Build & push image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:$IMAGE_TAG .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:$IMAGE_TAG
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:$IMAGE_TAG \
                     ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:latest

      # Deploy new image to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/hrms-backend:latest
